### ISSUE TITLE
Failled to build .so library 

### ISSUE THREAD

**Issue by sucrecacao** [tree-sitter/py-tree-sitter#43]
After installing tree sitter with and importing the library as explain in the README, the following command :
```python
>>> from tree_sitter import Language, Parser
>>> Language.build_library(
... 'build/test_tree_sitter.so',
... ['path/to/tree-sitter-python'])
```

Got the following error:

```
/usr/bin/ld: cannot find -lc++abi
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/usr/lib/python3.7/distutils/unixccompiler.py", line 215, in link
    self.spawn(linker + ld_args)
  File "/usr/lib/python3.7/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'cc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/joe/.local/lib/python3.7/site-packages/tree_sitter/__init__.py", line 72, in build_library
    compiler.link_shared_object(object_paths, output_path)
  File "/usr/lib/python3.7/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/usr/lib/python3.7/distutils/unixccompiler.py", line 217, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'cc' failed with exit status 1
```

**Comment by sucrecacao** [comment]
Fixed with the following:
```
sudo apt install libc++abi-dev  
```
Should this be in the readme too ?

**Comment by boba-and-beer** [comment]
^ This solution did not work for me.

**Comment by sucrecacao** [comment]
Did you got also 
`/usr/bin/ld: cannot find -lc++abi` 
( or could you paste the hole error message?)
